### ISSUE TITLE
How to add proxy settings?

### ISSUE THREAD

**Issue by SSEsmaeeli** [gabrie30/ghorg#101]
Is it possible to add proxy setting for getting repositories data?

e.g. `ghorg clone myUsername --clone-type=user --scm=gitlab --token=someToken --proxyType=socks5 proxyAddr=127.0.0.1:9050`.

acctually I add `--proxyType=socks5` and `proxyAddr=127.0.0.1:9050` in my own, so my question is that is it possible to do something like this ? or you considered before and now you can help me with it's keyword of adding proxy settings?

Thanks.

**Comment by gabrie30** [comment]
https://github.com/gabrie30/ghorg/blob/master/examples/gitlab.md take a look at the github examples, there is no proxyType flag in ghorg. You can try the `--base-url=`

**Comment by SSEsmaeeli** [comment]
> https://github.com/gabrie30/ghorg/blob/master/examples/gitlab.md take a look at the github examples, there is no proxyType flag in ghorg. You can try the `--base-url=`

Yeah I saw the given link, but I want to connect to main Gitlab server, 
So we can not set proxy in order to connect to Gitlab servers? 
any change to implement it? or not possible soon ?

**Comment by gabrie30** [comment]
Won't be possible anytime soon

**Comment by GitarPlayer** [comment]
> Won't be possible anytime soon, here's why:
I agree it would be a handful. As https://pkg.go.dev/os/exec#example-Cmd.Run does not invoke the system shell and does not expand any glob patterns or handle other expansions, pipelines, or redirections typically done by shells. And git by default looks at  [path]/etc/gitconfig, ~/.gitconfig (or ~/.config/git/config) and I think because of how os.exec is written those will not be read at all. I tried setting the proxy in those files but it would not work, while a manual git pull would work.
A workaround:
in ~/.bashrc define an alias:
`
# customize your ghorg command as you wish
alias proxy_ghorgh='HTTPS_PROXY=http://your.proxy.com:8080 ghorg clone all-groups --base-url=https://your.scm.com/ --scm=gitlal --token=$YOUR_TOKEN --preserve-dir'
`
This way ghorg honors the proxy. I hope it helps.

**Comment by mlaily** [comment]
Defining an environment variable with `HTTPS_PROXY=http://your.proxy.com:8080` does the trick pretty well!  
(I just wanted to see what requests ghorg was doing with [fiddler](https://www.telerik.com/download/fiddler))
