### ISSUE TITLE
Produce non-zero exitcode on errors?

### ISSUE THREAD

**Issue by i3v** [gabrie30/ghorg#208]
**Is your feature request related to a problem? Please describe.**
When something goes wrong with the clone process, the `============ Issues ============` section is [printed](https://github.com/gabrie30/ghorg/blob/cd74048b107fc049ae19cf215f08b3e9df073931/cmd/clone.go#L291) to stdout. 
However, the "ghorg.exe" exit code is still zero. This could be somewhat inconvenient for automated use (or, at least, unexpected).

**Describe the solution you'd like**
I'd suggest to exit with a non-zero exit code when something fails and the process is not finished successfully.

**Describe alternatives you've considered**
It would be nice to document down what happens when something goes wrong, at least (e.g. that user should not expect non-zero exit code).

**Comment by gabrie30** [comment]
There are a handful of cases where ghorg will exit 1, however as you mention the issues currently are not one of them. 

I see your point with exiting 1 with the issues tho for automation purposes

Adding an exit code now might mess up current automation so I'm a bit hesitant. Also, the cloning issues can occur for many reasons, some of which might not be a reason to return an exit code of 1. 

I think ideally there might be 3 categories instead of the current 2 (success and issues). Perhaps successes, warnings, and errors (or something similar to this). The warnings would be for cloning issues that don't require an exit code, but if anything in the errors category occurred while cloning a repo ghorg would exit 1.

**Comment by i3v** [comment]
I'm not sure exactly, how such warnings should work... After all, when `============ Issues ============` is printed, it is a sort of warning as well... (But it looks like it's not documented and thus might change in some later version without any notice.)

Maybe, instead of creating some special "warnings category", there rather should be an `exitcode_on_clone_issues` input parameter,  

* It could be zero by default, to not break the current behavior. 
* Those users who would like to handle it just the same as `exitcode==1` case could just assign it to `1`
* Those users who would like to handle it separately from `exitcode==1` case could just assign it to `2`

**Comment by gabrie30** [comment]
Great idea!

**Comment by gabrie30** [comment]
After looking into this a bit further, I think your original proposal is the correct behavior. I was thinking we were discussing "Info" by accident. 

That being said the new behavior will be exit 1 on any **_Issues_** and allowing users to determine the exit code on any **_Infos_** with the default being 0
