### ISSUE TITLE
`git-bundle` support

### ISSUE THREAD

**Issue by treylav** [gabrie30/ghorg#278]
Hello.

First of all, thanks for the useful tool.

Maybe I'm wrong, but I didn't find the repository packaging into [git bundle](https://git-scm.com/docs/git-bundle) among the `ghorg` features. In the meantime, this is a popular way to store repositories for backup: one file output, compression (although basic) without external software. It seems to me that it would be a logical addition to the functionality of `ghorg`.

Thanks in advance.

**Comment by gabrie30** [comment]
Thanks for sharing! Will probably implement when I have some time.

**Comment by gabrie30** [comment]
Took a look at this, ghorg currently uses `clone --mirror` when the `--backup` flag is enabled. Cloning as a mirror seems like a better option for backups than `git bundle` since it captures all the branches. Going to close this as the current backup method is sufficient. But was interesting to read about this method as well appreciate you opening this issue.
