### ISSUE TITLE
Support Github Application token

### ISSUE THREAD

**Issue by duizabojul** [gabrie30/ghorg#306]
I think using a PAT for cloning org repos is a bad practice. I tried to use a github application access token instead but got Error: exit status 128 when ghorg tries to clone private repos.

**Comment by gabrie30** [comment]
You can alternatively use an ssh key to clone repos.

**Comment by duizabojul** [comment]
Is it possible to create a ssh key for an organization? We don't want  to have a user scoped authentication to do this kind of thing (backup an entire org)

**Comment by gabrie30** [comment]
Oh I see thanks for the additional details.

You would need to create a robot user that has read permissions to all repos. Then use that robot users credentials, ssh keys would work with this too. Also GitHub has fine grained PAT now if your org enables it. I would assume you could create a read only token from one of your admin users and use that.

The Github App auth isn't currently supported, seems like it would be a nice addition, but not sure when I'll have the time to look into it more. I'm assuming you want to use the GitHub app because you can easily give it access to all repos?

**Comment by duizabojul** [comment]
We prefer using Github app to avoid using users when we are doing "machine" related stuff (and Github users are not free in paid plans 😬).

Btw, if it would be better to handle the full authentication process of a Github app, I think the fix to allow using an [installation access token](https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/generating-an-installation-access-token-for-a-github-app) should be pretty small. The only difference of an installation access token with a PAT is there is no user attached to it.

**Comment by gabrie30** [comment]
@duizabojul I have a fix on the main branch if you want to try it out

**Comment by duizabojul** [comment]
Wow that's impressive reactivity  👏 I'll try it this week-end, thx for the effort 🙏

**Comment by gabrie30** [comment]
Was a fun one. Let me know how it goes and I'll cut a new release.
