### ISSUE TITLE
Latest image is not latest

### ISSUE THREAD

**Issue by fey** [gabrie30/ghorg#409]
**Please check the following resources before opening an issue**

1. Review the [troubelshooting section](https://github.com/gabrie30/ghorg#troubleshooting) in the README.md
1. Review the [examples](https://github.com/gabrie30/ghorg/tree/master/examples) directory for example commands

**Describe the bug**
`ghcr.io/gabrie30/ghorg:latest` do not contain `openssh-client`

**To Reproduce**
`docker pull ghcr.io/gabrie30/ghorg:latest` and try to clone repositories via ssh

```docker run --rm -it --entrypoint /bin/sh ghcr.io/gabrie30/ghorg:latest
/data $ whoami
ghorg
/data $ ssh
/bin/sh: ssh: not found
/data $ 
```

![image](https://github.com/gabrie30/ghorg/assets/697178/58030fb0-2d4d-4da6-92e5-9707d0e2cce2)
![image](https://github.com/gabrie30/ghorg/assets/697178/5767fb97-db25-4102-8268-24d8427bdd79)

**Comment by gabrie30** [comment]
The `latest` tag is for the latest release https://github.com/gabrie30/ghorg/blob/master/.github/workflows/docker-build-release.yml#L46

That change in the Dockerfile has only been pushed to the master branch, it hasn't been cut in a release yet. Once there is a release you can use the latest tag. However since its not released you need to use the `master` tag.

**Comment by gabrie30** [comment]
@fey the latest image will give you what you want now
