### ISSUE TITLE
Ability to pass a --filter option to git clone

### ISSUE THREAD

**Issue by ryanaross** [gabrie30/ghorg#80]
Since I mostly use ghorg for text search, it would be helpful for disk usage and speed if I could pass "--filter=blob:none" to `git clone` but we might as well make it so a user can pass their own custom filter too.

This requires Git 2.19 however

**Comment by Flavien-Pensato** [comment]
is'n it the same of `--match-regex` or `--match-prefix` ?

**Comment by gabrie30** [comment]
@Flavien-Pensato good question! Blob is an abbreviation for "binary large object" so you can filter out binaries that people have committed into a repo. The filter happens in the process of cloning a repo. Binaries can take up large amounts of space on your hard drive especially if you clone a lot of repos. Since the OP only uses the ghorg directory to search for text the binary files dont serve any purpose other than taking up space, so he wants to filter them out.

The flags like `--match-prefix` filter out repos, before they are even cloned, by looking at the name of the repo and comparing it to the flag. For example, if you cloned all of the github user `gabrie30` repos and used the `--match-prefix=ghorg` you would only clone one repo because I have no other repos that have the prefix ghorg in them.
